name: 'greentrail'
version: '1.0.0'

profile: 'greentrail'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  greentrail:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
